; Masked LSTM Config Test
; Author: Dillon Allen
; Last Edit: 3/30/2026

; Purpose:
; This init file is meant for unifying the parameters used for the 
; sliding window computations (finding ideal window size for each feature)
; and then using these ideal window sizes to put into a LSTM with a given masking
; This should contain train/test split factor, input size, hidden layer size, 
; etc. 
; Additionally, this is to test for the PFI dataset

[lstm_params]
learning_rate = 8e-3
dropout       = 0.4
epochs        = 120
train_frac    = 0.75
hidden_size   = 32
weight_decay  = 1e-5
num_layers    = 2

[pipeline_params]
run_pfi       = True
